name: Increase my age

on:
  schedule:
    - cron: "0 1 13 6 *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: node packages/age
      # - run: node packages/age # run readme build

      - name: Commit changes
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          message: 'chore: update age in readme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
